import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import QueryProvider from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "sparta Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <Link className="px-4" href="/">
            홈
          </Link>
          <Link className="px-4" href="/about">
            about
          </Link>
          <Link className="px-4" href="/contact">
            contact
          </Link>
          <Link className="px-4" href="/blog">
            blog
          </Link>
        </nav>

        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
